name: build_date_gen
description: Generates a build date.
version: 0.0.1
author: Pinkfish
homepage: https://github.com/pinkfish/flutter_basketball

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  basketballdata:
    path: ../basketballdata
  build: ^1.3.0
  source_gen: ^0.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^1.2.0
  build_runner: ^1.10.0
  test: ^1.15.0

flutter:
