name: basketballstats
description: Basketball statistics tracking app.

version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  basketballdata:
    path: ../basketballdata
  firebase_auth: 0.15.0
  firebase_analytics: ^5.0.11
  firebase_core: 0.4.4
  firebase_crashlytics: ^0.1.3
  google_sign_in: ^4.1.4
  flutter_bloc: ^3.2.0
  cloud_firestore: 0.13.4
  intl: ^0.16.0
  fluro: ^1.6.2
  sqflite: ^1.2.1
  material_design_icons_flutter: ^4.0.5045
  equatable: ^1.1.1
  undo: ^1.0.1+3
  uuid: ^2.0.4
  tuple: ^1.0.3
  flutter_svg: ^0.17.3+1
  charts_flutter:
    #path: /Users/david/development/charts/charts_flutter
    git:
      url: https://github.com/pinkfish/charts.git
      path: charts_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  intl_translation: ^0.17.9
  screenshots:
    git:
      url: https://github.com/pinkfish/screenshots.git



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/abstractsport.png
    - assets/images/basketball.png
    - assets/images/google_logo.png
    - assets/images/Basketball_Halfcourt.svg
    - assets/images/Basketball_Halfcourt_light.svg
