name: basketballstats
description: Basketball statistics tracking app.

homepage: https://basketballstats-8ed93.web.app/
version: 0.3.4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  basketballdata:
    path: ../basketballdata
  firebase_core: 0.4.4
  firebase_auth: 0.15.2
  firebase_analytics: ^5.0.16
  firebase_crashlytics: ^0.1.4+1
  firebase_storage: ^3.1.6
  firebase_performance: ^0.3.2
  cloud_functions: ^0.5.0
  localstorage: ^3.0.2+5

  google_sign_in: ^4.5.1
  flutter_bloc: ^6.0.1
  hydrated_bloc: ^6.0.1
  cloud_firestore: 0.13.4
  intl: ^0.16.1
  fluro: ^1.6.3
  sqflite: ^1.3.1
  material_design_icons_flutter: ^4.0.5345
  flutter_speed_dial: ^1.2.5
  equatable: ^1.2.3
  undo: ^1.2.0+1
  uuid: ^2.2.0
  tuple: ^1.0.3
  image: ^2.1.12
  flutter_svg: ^0.18.0
  flutter_vector_icons: any
  event: ^1.1.4
  settings_ui: ^0.3.0
  keyboard_visibility: ^0.5.6
  package_info: ^0.4.1
  charts_flutter:
    #path: /Users/david/development/charts/charts_flutter
    git:
      url: https://github.com/pinkfish/charts.git
      path: charts_flutter

  # Lightweight localstorage
  hive: ^1.4.3
  hive_flutter: ^0.3.1

  # For doing things with video
  camera_with_rtmp: ^0.3.2
  video_player: 0.10.11+2
  cached_network_image: ^2.2.0+1
  image_picker: ^0.6.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  intl_translation: ^0.17.9
  screenshots:
    git:
      url: https://github.com/pinkfish/screenshots.git



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/abstractsport.png
    - assets/images/basketball.png
    - assets/images/google_logo.png
    - assets/images/Basketball_Halfcourt.svg
    - assets/images/Basketball_Halfcourt_light.svg
    - assets/images/hands_and_trophy.png
    - assets/icons/seasons.svg

flutter_intl:
  enabled: true
