# This is a basic workflow to help you get started with Actions

name: Firebase functions

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ main ]
    paths: 
      - "firebase/functions/**"
      - ".github/workflows/firebase_functions.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "firebase/functions/**"
      - ".github/workflows/firebase_functions.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: firebase/functions
      - name: Copy assets
        run: cp ux/assets/images/basketball.png firebase/functions/src/db/templates/invites/img/defaultteam.jpg
      - name: Build
        run: npm run build
        working-directory: firebase/functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.firebaseToken }}
          PROJECT_PATH: firebase
          PROJECT_ID: basketballstats-8ed93
