name: Flutter - ios

on: 
  release:
    types: [created,edited]

jobs:
  build:
   runs-on: self-hosted

   steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Dump env
      run: |
        echo ${SOURCE_TAG}
        echo ${SOURCE_BRANCH}
        echo ${SOURCE_TAG}
        echo ${{ GITHUB.ref }}
      env:
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    - uses: subosito/flutter-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
        channel: 'stable' # or: 'dev' or 'beta'
    - run: flutter pub get
      working-directory: basketballdata
    - run: flutter pub run build_runner build
      working-directory: basketballdata
    - run: flutter packages get
      working-directory: ux
    - run: brew install graphicsmagick
      working-directory: ux
    - run: echo ${GOOGLESERVICES} > ios/Runner/GoogleService-Info.plist
      working-directory: ux	
      env: 	
        GOOGLESERVICES: ${{ secrets.googleservicesIos }}
    - run: echo ${FASTLANE} > ~/app-fastlane.json	
      working-directory: ux	
      env: 	
        FASTLANE: ${{ secrets.fastlaneApp }}
    - run: pod install	
      working-directory: ux/ios
    - run: brew install graphicsmagick
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: beta
        subdirectory: ux/ios
        bundle-install-path: ux/ios/packages
        options: '{"version": "${{ steps.branch_name.outputs.SOURCE_TAG }}"}'
      env:
        FASTLANE_SESSION: ${{ secrets.FASTLANE_APPLE_SESSION }}
        FL_GITHUB_RELEASE_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLEAPPSPECIFICPASSWORD }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 10 # Longer timeout for the build settings.
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Release notes for the ios ${{ steps.branch_name.outputs.SOURCE_TAG}} version" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
