name: Flutter - ios

on: 
  release:
    types: [created,edited]

jobs:
  build:
   runs-on: self-hosted

   steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
        channel: 'stable' # or: 'dev' or 'beta'
    - run: flutter pub get
      working-directory: basketballdata
    - run: flutter pub run build_runner build
      working-directory: basketballdata
    - run: flutter packages get
      working-directory: ux
    - run: echo ${GOOGLESERVICES} > ios/Runner/GoogleService-Info.plist	
      working-directory: ux	
      env: 	
        GOOGLESERVICES: ${{ secrets.googleservicesIos }}
    - run: echo ${FASTLANE} > ~/app-fastlane.json	
      working-directory: ux	
      env: 	
        FASTLANE: ${{ secrets.fastlaneApp }}
    - run: pod install	
      working-directory: ux/ios
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: beta
        subdirectory: ux/ios
        bundle-install-path: ux/ios/packages
        options: '{"version": "${{ github.ref }}"}'
      env:
        FASTLANE_SESSION: ${{ secrets.FASTLANE_APPLE_SESSION }}
        FL_GITHUB_RELEASE_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLEAPPSPECIFICPASSWORD }}  
    - uses: matheusalbino/git-commit@v1.0.1
      with:
        user-name: pinkfishfrog
        user-email: pinkfishfrog@gmail.com
        message: Change notes for the new release.
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Required
        commit_message: Apply automatic changes

        # Optional options appended to `git-commit`
        commit_options: '--no-verify --signoff'

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: GitHub Actions Bot
        commit_user_email: my-github-actions-bot@example.org
        commit_author: Author <actions@github.com>

        # Force update the tag to the new location.
        tagging_message: ${{ steps.branch_name.outputs.SOURCE_TAG }}

        # Optional options appended to `git-push`
        push_options: '--force'