name: Flutter

on: 
  push:
    branches: [master]
    paths: 
      - ux/**
      - firebasedata/**
      -  .github/workflows/flutter-ios.yml


jobs:
  build:
   runs-on: self-hosted

   steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
        channel: 'stable' # or: 'dev' or 'beta'
    - run: flutter pub get
      working-directory: basketballdata
    - run: flutter pub run build_runner build
      working-directory: basketballdata
    - run: flutter packages get
      working-directory: ux
    - run: echo ${GOOGLESERVICES} > ios/Runner/GoogleService-Info.plist	
      working-directory: ux	
      env: 	
        GOOGLESERVICES: ${{ secrets.googleservicesIos }}
    - run: echo ${FASTLANE} > ~/app-fastlane.json	
      working-directory: ux	
      env: 	
        FASTLANE: ${{ secrets.fastlaneApp }}
    - run: pod install	
      working-directory: ux/ios
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: beta
        subdirectory: ux/ios
      env:
        FASTLANE_SESSION: ${{ secrets.appleFastlaneSession }}
    - uses: matheusalbino/git-commit@v1.0.1
      with:
        user-name: pinkfishfrog
        user-email: pinkfishfrog@gmail.com
        message: Change notes for the new release.
        github-token: ${{ secrets.GITHUB_TOKEN }}
