name: CI

on: [push]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
        channel: 'stable' # or: 'dev' or 'beta'
    - uses: axel-op/dart-package-analyzer@v2.0.0
      with:
        # Required:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        # Optional:
        relativePath: ux
    # You can then use this id to retrieve the outputs in the next steps.
    # The following step shows how to exit the workflow with an error if a score is below 100:
    - name: Check scores
      run: |
        MAINTENANCE_SCORE=${{ steps.analysis.outputs.maintenance }}
        HEALTH_SCORE=${{ steps.analysis.outputs.health }}
        if (( $(echo "$MAINTENANCE_SCORE < 100" | bc) )) || (( $(echo "$HEALTH_SCORE < 100" | bc) ))
        then
          echo "Scores are not both equal to 100"
          exit 1
        fi
    - uses: axel-op/dart-package-analyzer@v2.0.0
      with:
        # Required:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        # Optional:
        relativePath: basketballdata
    # You can then use this id to retrieve the outputs in the next steps.
    # The following step shows how to exit the workflow with an error if a score is below 100:
    - name: Check scores
      run: |
        MAINTENANCE_SCORE=${{ steps.analysis.outputs.maintenance }}
        HEALTH_SCORE=${{ steps.analysis.outputs.health }}
        if (( $(echo "$MAINTENANCE_SCORE < 100" | bc) )) || (( $(echo "$HEALTH_SCORE < 100" | bc) ))
        then
          echo "Scores are not both equal to 100"
          exit 1
        fi
    # Set up git with key and domain
    - name: 'gcr.io/cloud-builders/git'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      shell: bash
      run: |
          mkdir -p ~/.ssh
          echo ${GUTHUB_TOKEN} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOF >~/.ssh/config
          Hostname github.com
          IdentityFile ~/.ssh/id_rsa
          EOF
          ssh-keyscan -t rsa github.com > known_hosts
          mv known_hosts ~/.ssh/known_hosts
    - run: git config --global url.”https://{token}:@github.com/".insteadOf “https://github.com/"
      working-directory: ux
    - run: flutter pub get
      working-directory: ux
    - run: flutter pub get
      working-directory: basketballdata
    - run: echo ${GOOGLESERVICES} > android/app/google-services.json
      working-directory: ux
      env: 
        GOOGLESERVICES: ${{ secrets.googleservicesAndroid }}
    - run: flutter pub run build_runner build
      working-directory: basketballdata
    #- run: flutter test
    #  working-directory: ux
    - run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64
      working-directory: ux
