name: CI

on: [push]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'dev' or 'beta'
    - run: flutter pub get
      working-directory: ux
    - run: flutter pub get
      working-directory: basketballdata
    - run: flutter pub run build_runner build
      working-directory: basketballdata
    #- run: flutter test
    #  working-directory: ux
    - run: flutter build apk
      working-directory: ux
